begin;

create table if not exists public.spot_merge_backups (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  kept_spot_id uuid not null,
  removed_spot_id uuid not null,
  spot_data jsonb not null,
  related_data jsonb not null
);

alter table public.spot_merge_backups enable row level security;
revoke all on table public.spot_merge_backups from anon, authenticated;

do $$
declare
  pair record;
  kept public.spots%rowtype;
  removed public.spots%rowtype;
begin
  for pair in
    select *
    from (
      values
        ('643ef621-f628-4c22-a322-64fa6b41420a'::uuid, '786ff4bd-9cc7-4637-a1e4-2d73f0a3626f'::uuid),
        ('24dc04cb-2b8e-40f5-8449-2a3c036088d4'::uuid, 'f292009e-f76e-4e5d-bb47-a3ac6bb6093f'::uuid),
        ('7b624ed6-7c15-4e83-8a52-30125a8fd60d'::uuid, 'd01e59bb-7132-40c6-991c-353cc0d9ac1c'::uuid),
        ('a74770a8-c07e-4347-9d64-5c3e4087161e'::uuid, '2d1d1697-26cc-48e3-99f4-7ba110e2094e'::uuid),
        ('c9f3ee62-beb5-43b6-8d47-1f7c2fd05f1a'::uuid, '227e4cb8-11c6-4e95-9263-810b8038140c'::uuid),
        ('b0c6786f-a824-4ba7-95ac-9f2e3800ff1b'::uuid, '2c65433b-0815-4e37-a47b-06a5a300915f'::uuid),
        ('2b08b365-abb3-438e-8a6c-80e3fcc69f5d'::uuid, '838a3c50-a32a-4510-b91b-f457b9a3d3b3'::uuid)
    ) as pairs(keep_id, remove_id)
  loop
    select * into strict kept from public.spots where id = pair.keep_id;
    select * into strict removed from public.spots where id = pair.remove_id;

    if kept.name is distinct from removed.name
      or kept.lat is distinct from removed.lat
      or kept.lng is distinct from removed.lng
      or kept.description is distinct from removed.description then
      raise exception 'Spot pair % / % is no longer an exact duplicate', pair.keep_id, pair.remove_id;
    end if;

    insert into public.spot_merge_backups (
      kept_spot_id,
      removed_spot_id,
      spot_data,
      related_data
    )
    values (
      pair.keep_id,
      pair.remove_id,
      to_jsonb(removed),
      jsonb_build_object(
        'spot_checkins', coalesce((select jsonb_agg(to_jsonb(row_data)) from public.spot_checkins row_data where spot_id = pair.remove_id), '[]'::jsonb),
        'visit_logs', coalesce((select jsonb_agg(to_jsonb(row_data)) from public.visit_logs row_data where spot_id = pair.remove_id), '[]'::jsonb),
        'route_spots', coalesce((select jsonb_agg(to_jsonb(row_data)) from public.route_spots row_data where spot_id = pair.remove_id), '[]'::jsonb),
        'user_spot_durations', coalesce((select jsonb_agg(to_jsonb(row_data)) from public.user_spot_durations row_data where spot_id = pair.remove_id), '[]'::jsonb),
        'spot_characters', coalesce((select jsonb_agg(to_jsonb(row_data)) from public.spot_characters row_data where spot_id = pair.remove_id), '[]'::jsonb),
        'spot_episodes', coalesce((select jsonb_agg(to_jsonb(row_data)) from public.spot_episodes row_data where spot_id = pair.remove_id), '[]'::jsonb),
        'spot_significance_tags', coalesce((select jsonb_agg(to_jsonb(row_data)) from public.spot_significance_tags row_data where spot_id = pair.remove_id), '[]'::jsonb)
      )
    );

    insert into public.spot_checkins (
      user_id,
      spot_id,
      first_visited_at,
      is_favorite
    )
    select
      user_id,
      pair.keep_id,
      first_visited_at,
      is_favorite
    from public.spot_checkins
    where spot_id = pair.remove_id
    on conflict (user_id, spot_id) do update
    set
      first_visited_at = least(
        public.spot_checkins.first_visited_at,
        excluded.first_visited_at
      ),
      is_favorite = public.spot_checkins.is_favorite or excluded.is_favorite;
    delete from public.spot_checkins where spot_id = pair.remove_id;

    update public.visit_logs
    set spot_id = pair.keep_id
    where spot_id = pair.remove_id;

    delete from public.route_spots duplicate_route_spot
    using public.route_spots kept_route_spot
    where duplicate_route_spot.spot_id = pair.remove_id
      and kept_route_spot.spot_id = pair.keep_id
      and kept_route_spot.route_id = duplicate_route_spot.route_id;
    update public.route_spots
    set spot_id = pair.keep_id
    where spot_id = pair.remove_id;

    insert into public.user_spot_durations (user_id, spot_id, duration_min)
    select user_id, pair.keep_id, duration_min
    from public.user_spot_durations
    where spot_id = pair.remove_id
    on conflict (user_id, spot_id) do nothing;
    delete from public.user_spot_durations where spot_id = pair.remove_id;

    insert into public.spot_characters (spot_id, character_id)
    select pair.keep_id, character_id
    from public.spot_characters
    where spot_id = pair.remove_id
    on conflict (spot_id, character_id) do nothing;
    delete from public.spot_characters where spot_id = pair.remove_id;

    insert into public.spot_episodes (spot_id, episode_id, scene_description, scene_description_en)
    select pair.keep_id, episode_id, scene_description, scene_description_en
    from public.spot_episodes
    where spot_id = pair.remove_id
    on conflict (spot_id, episode_id) do update
    set
      scene_description = coalesce(
        public.spot_episodes.scene_description,
        excluded.scene_description
      ),
      scene_description_en = coalesce(
        public.spot_episodes.scene_description_en,
        excluded.scene_description_en
      );
    delete from public.spot_episodes where spot_id = pair.remove_id;

    insert into public.spot_significance_tags (spot_id, tag_id)
    select pair.keep_id, tag_id
    from public.spot_significance_tags
    where spot_id = pair.remove_id
    on conflict (spot_id, tag_id) do nothing;
    delete from public.spot_significance_tags where spot_id = pair.remove_id;

    delete from public.travel_times
    where from_spot_id = pair.remove_id or to_spot_id = pair.remove_id;

    delete from public.spots where id = pair.remove_id;
  end loop;
end
$$;

commit;
